/**
 * Mobile Banking App Test - Real-World Example
 *
 * Tests mobile banking features on iOS and Android devices
 * Demonstrates Nexus QA mobile testing capabilities
 *
 * 🚀 Auto-generated by Nexus QA Mobile Testing System
 */

import { test, expect } from '@playwright/test';
import { smartTap, smartSwipe, smartFillMobile, smartScrollMobile } from '../helpers/mobileSmartActions.js';
import { getDeviceConfig } from '../../src/config/mobileDevices.js';

test.describe('Mobile Banking App - iOS & Android', () => {
  // Test on both platforms
  const devices = ['iPhone 15 Pro', 'Samsung Galaxy S24 Ultra'];

  devices.forEach((deviceName) => {
    test.describe(`${deviceName}`, () => {
      test.beforeEach(async ({ page, context }) => {
        const config = getDeviceConfig(deviceName);
        await page.setViewportSize(config.viewport);
        await context.setExtraHTTPHeaders({
          'User-Agent': config.userAgent
        });

        console.log(`📱 Testing on ${deviceName} (${config.platform})`);
      });

      test(`Login and Check Balance - ${deviceName}`, async ({ page }) => {
        // Navigate to mobile banking app
        await page.goto('https://www.isbank.com.tr');

        // Tap mobile menu
        await smartTap(page, 'text=☰', { retryWithVision: true });

        // Tap "Bireysel" (Personal Banking)
        await smartTap(page, 'text=Bireysel', { retryWithVision: true });

        // Scroll to find accounts section
        await smartScrollMobile(page, 'text=Hesaplarım', {
          direction: 'down',
          maxScrolls: 5
        });

        // Tap on "Hesaplarım" (My Accounts)
        await smartTap(page, 'text=Hesaplarım', { retryWithVision: true });

        // Verify redirected to login or accounts page
        await page.waitForTimeout(2000);
        const currentUrl = page.url();
        console.log(`Current URL: ${currentUrl}`);

        // Take screenshot
        await page.screenshot({ path: `./screenshots/${deviceName}-accounts.png` });
      });

      test(`Swipe Through Product Carousel - ${deviceName}`, async ({ page }) => {
        await page.goto('https://www.isbank.com.tr');

        // Find carousel
        const carouselExists = await page.locator('[class*="carousel"], [class*="slider"]').first().isVisible().catch(() => false);

        if (carouselExists) {
          // Swipe left through carousel
          for (let i = 0; i < 3; i++) {
            await smartSwipe(page, 'left', {
              element: '[class*="carousel"], [class*="slider"]',
              distance: 300,
              duration: 300
            });

            await page.waitForTimeout(500);
          }

          console.log('✓ Carousel swipe completed');
        } else {
          console.log('ℹ No carousel found on page');
        }
      });

      test(`Mobile Form Fill - ${deviceName}`, async ({ page }) => {
        await page.goto('https://www.isbank.com.tr');

        // Tap "İletişim" (Contact)
        await smartTap(page, 'text=İletişim', { retryWithVision: true });

        await page.waitForTimeout(1000);

        // If contact form exists, fill it (mobile optimized)
        const nameInput = await page.locator('input[name="name"], input[id="name"]').first().isVisible().catch(() => false);

        if (nameInput) {
          await smartFillMobile(page, 'input[name="name"], input[id="name"]', 'Ahmet Ercikan', {
            retryWithVision: true
          });

          await smartFillMobile(page, 'input[type="email"]', 'test@example.com', {
            retryWithVision: true
          });

          await smartFillMobile(page, 'input[type="tel"]', '+905551234567', {
            retryWithVision: true
          });

          console.log('✓ Form filled successfully');
        }

        await page.screenshot({ path: `./screenshots/${deviceName}-contact-form.png` });
      });

      test(`Responsive Navigation Menu - ${deviceName}`, async ({ page }) => {
        await page.goto('https://www.isbank.com.tr');

        // Tap hamburger menu
        await smartTap(page, '[class*="menu"], [class*="hamburger"], text=☰', {
          retryWithVision: true
        });

        await page.waitForTimeout(500);

        // Verify menu opened
        const menuVisible = await page.locator('[class*="mobile-menu"], [class*="sidebar"], [class*="drawer"]').isVisible().catch(() => false);

        if (menuVisible) {
          console.log('✓ Mobile menu opened');

          // Tap first menu item
          await smartTap(page, '[class*="mobile-menu"] a, [class*="sidebar"] a', {
            retryWithVision: true
          });

          await page.waitForTimeout(1000);
          console.log('✓ Menu navigation completed');
        } else {
          console.log('ℹ Mobile menu not detected');
        }
      });

      test(`Mobile Pull-to-Refresh Simulation - ${deviceName}`, async ({ page }) => {
        await page.goto('https://www.isbank.com.tr');

        // Simulate pull-to-refresh gesture
        await smartSwipe(page, 'down', {
          startY: 100,
          distance: 200,
          duration: 500
        });

        await page.waitForTimeout(1500);

        console.log('✓ Pull-to-refresh gesture completed');

        // Take screenshot after refresh
        await page.screenshot({ path: `./screenshots/${deviceName}-after-refresh.png` });
      });
    });
  });

  // Cross-device comparison test
  test('Compare iOS vs Android Rendering', async ({ page }) => {
    const results = [];

    for (const deviceName of devices) {
      const config = getDeviceConfig(deviceName);
      await page.setViewportSize(config.viewport);

      await page.goto('https://www.isbank.com.tr');
      await page.waitForLoadState('networkidle');

      // Capture metrics
      const metrics = await page.evaluate(() => {
        return {
          viewport: {
            width: window.innerWidth,
            height: window.innerHeight
          },
          hasHorizontalScroll: document.documentElement.scrollWidth > window.innerWidth,
          bodyHeight: document.body.scrollHeight
        };
      });

      results.push({
        device: deviceName,
        platform: config.platform,
        ...metrics
      });
    }

    console.log('📊 Cross-Device Comparison:', JSON.stringify(results, null, 2));

    // Assert both platforms render without horizontal scroll
    results.forEach(result => {
      expect(result.hasHorizontalScroll).toBe(false);
    });
  });
});
